apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vmsingle-ingress
  namespace: vmetrics
spec:
  ingressClassName: traefik
  rules:
  - host: metrics.localtest.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vmsingle-vmks-victoria-metrics-k8s-stack
            port:
              number: 8428
